jupyterhub::jupyterhub_config_hash:
    SbatchForm:
        runtime:
            min: 3.5
            def: 4.0
            max: 5.0
        nprocs:
            min: 1
            def: 1
            max: 1
        memory:
            min: 1024
            max: 2048
            def: 2048
        oversubscribe:
            def: true
            lock: true
        ui:
            def: 'lab'
    SlurmFormSpawner:
        disable_form: true

jupyterhub::enable_otp_auth: false

jupyterhub::admin_groups: ['user55', 'user54', 'user53', 'user52', 'user51']

jupyterhub::kernel::venv::packages: ['numpy', 'pandas', 'matplotlib']

profile::freeipa::mokey::enable_user_signup: false

profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020']
